begin;

create table if not exists public.learning_notes (
  id bigint generated by default as identity primary key,
  owner_id uuid,
  title text not null check (char_length(title) between 1 and 120),
  content text not null check (char_length(content) between 1 and 2000),
  created_at timestamptz not null default now()
);

alter table public.learning_notes enable row level security;
revoke all on table public.learning_notes from anon, authenticated;
grant select on table public.learning_notes to service_role;

commit;

-- Intentionally no SELECT policy for anon/authenticated.
-- owner_id is deliberately not a foreign key to auth.users in step 2.
-- Insert the four training rows in Supabase SQL Editor only; do not commit their plaintext.
